# Generated by Django 5.0.6 on 2024-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=15, unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("owner_contact", models.CharField(max_length=15)),
                ("owner_email", models.EmailField(max_length=254)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_color", models.CharField(max_length=100)),
            ],
        ),
    ]
