# Generated by Django 5.0.6 on 2024-07-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_manufacturer",
            field=models.CharField(default="", max_length=100),
        ),
    ]
